### PR TITLE
Three pointless moves

### PR DESCRIPTION
**Pull request by thechurchofcage**
Celebrate, Hold Hands and Happy Hour. Yay(!)

### CODE REVIEW

**Comment by Fontbane** [comment]
Happy Hour doubles prize money, like Amulet Coin.

**Comment by thechurchofcage** [comment]
OOPS

**Comment by DizzyEggg** [comment]
Actually, let's combine these effects with Splash. Call them MOVE_EFFECT_DUMB or sth like that

**Comment by thechurchofcage** [comment]
OK, if that's what you want :P

**Comment by DizzyEggg** [comment]
Do you think I'm dumb? :(

btw why is gBattleScripting.moveEffect &= ~(MOVE_EFFECT_CERTAIN); needed

**Comment by thechurchofcage** [comment]
:ecksdee:
Just a safety check in case that flag is still set, for whatever reason. SetMoveEffect breaks if it is.

**Pull request merged**
