### PR TITLE
Fix some move names for consistency w/main series games

### PR DESCRIPTION
**Pull request by Fontbane**
Fixed capitalization and hyphens in Gen 1-5 moves that were inconsistent with the DS games, and shortened/fixed some Gen 6-7 moves to better match the games.
I could shorten some Gen 6-7 moves further using their Japanese names but that might be too far a departure.

### CODE REVIEW

**Comment by DizzyEggg** [comment]
I'm not really a fan of two separate words jointed into one tbh

**Comment by Fontbane** [comment]
I mean, it's better than having one letter cut off, right?
I'll see what I can do to put spaces in there, though it wouldn't line up with canon names.

**Comment by DizzyEggg** [comment]
I'm not sure about these, I'll ask what others think of it.

**Comment by ultima-soul** [comment]
I'm fine with two words as one since that's technically what GF did for the moves originally to meet space requirements like Thunder Punch as THUNDERPUNCH. We should try to be most accurate as possible to localized names and if the only thing stopping that is having two complete words together, that's kinda silly.

**Pull request closed without merging**
