### PR TITLE
Parting Shot

### PR DESCRIPTION
**Pull request by thechurchofcage**
Effect plus animation (looks like Snarl)

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Looking good, but you should correct the last part of the Parting Shot's battle script. 

This
`
	jumpifcantswitch ATK4F_DONT_CHECK_STATUSES | BS_ATTACKER, BattleScript_MoveEnd
	openpartyscreen BS_ATTACKER, BattleScript_ButItFailed
	printstring STRINGID_PKMNWENTBACK
	switchoutabilities BS_ATTACKER
	waitstate
	switchhandleorder BS_ATTACKER, 0x2
	returnatktoball
	waitstate
	getswitchedmondata BS_ATTACKER
	switchindataupdate BS_ATTACKER
	hpthresholds BS_ATTACKER
	printstring STRINGID_SWITCHINMON
	switchinanim BS_ATTACKER, TRUE
	waitstate
	switchineffects BS_ATTACKER
	goto BattleScript_MoveEnd
`

to
`
setbyte sMOVEEND_STATE, 0x0
	moveend 0x0, 0x0
	jumpifcantswitch ATK4F_DONT_CHECK_STATUSES | BS_ATTACKER, BattleScript_PartingShotEnd
	openpartyscreen 0x1, BattleScript_PartingShotEnd
	switchoutabilities BS_ATTACKER
	waitstate
	switchhandleorder BS_ATTACKER, 0x2
	returntoball BS_ATTACKER
	getswitchedmondata BS_ATTACKER
	switchindataupdate BS_ATTACKER
	hpthresholds BS_ATTACKER
	printstring STRINGID_SWITCHINMON
	switchinanim BS_ATTACKER, TRUE
	waitstate
	switchineffects BS_ATTACKER
BattleScript_PartingShotEnd:
	end
`

**Comment by thechurchofcage** [comment]
OK, done! May I ask what your changes do exactly?

**Comment by DizzyEggg** [comment]
Basically, you need to account for move end's effect before the switch-in happens.

**Comment by DizzyEggg** [comment]
Also, you need to change
statbuffchange 0x1, BattleScript_MoveEnd
to point to a new label before
setbyte sMOVEEND_STATE, 0x0
begins.

Because currently, the switch-in doesn't happen if the pokemon can't have their sp.attack lowered.

**Comment by thechurchofcage** [comment]
Ah, sugar, that was a silly oversight on my part. OK, shall I make a new branch with a new pull request?

**Pull request merged**
