### PR TITLE
Updated Alphabetical, Weight and Height orders.

### PR DESCRIPTION
**Pull request by AsparagusEduardo**

### CODE REVIEW

**Comment by DizzyEggg** [comment]
Could you explain why the !temp_isHoennDex is necessary? What's the purpose of it?

**Comment by AsparagusEduardo** [comment]
From testing and looking at the code, vanilla sorting by name, weight or height only works for regional dex mons, even if the national dex option is chosen.
**NationalToHoennOrder(temp_dexNum) != 0** checks if the mon is part of the regional dex, so I added **|| !temp_isHoennDex** so see if the National Dex option is chosen, in which case it adds every mon to the list regardless if it's in the regional dex or not.

**Comment by DizzyEggg** [comment]
Oh, I see, that makes sense. Could you just swap the order of NationalToHoennOrder(temp_dexNum) != 0 || !temp_isHoennDex to  !temp_isHoennDex || NationalToHoennOrder(temp_dexNum) != 0?

That makes the loop a bit faster, since it calls a function only when necessary :)

**Comment by AsparagusEduardo** [comment]
Not sure if you got the notification, but I did it ^^;

**Comment by DizzyEggg** [comment]
Whoops, sorry. :P  Tho now that I look at it, you missed 3 cases

**Comment by DizzyEggg** [comment]
Thanks for your work!

**Pull request merged**
