### PR TITLE
Debug menu tied to BDEBUG

### PR DESCRIPTION
**Pull request by Gamer2020**
Makes it so the debug menu only shows if building with BDEBUG=1.

### CODE REVIEW

**Comment by SBird1337** [comment]
Just dropping in to mention that using `NDEBUG` is a common practice. You set `NDEBUG` for your release build, and it disables the debugging features. This is also how `AgbPrint` is handled iirc, and other debugging features should probably follow that style. I have already seen other implementations of EventScript debug menus that follow this convention.

Also: The flag can be set in `config.h` so there is no real need to have that in the Makefile.

**Comment by Gamer2020** [comment]
Yes but you have to manually make the change in the file every time correct? Having it in the makefile is more convenient and allows for different tasks for building.

For example, me and others are able to do this:

`        {
            "label": "Build Debug",
            "type": "shell",
            "promptOnClose": true,
            "command": "make DINFO=1 BDEBUG=1 -j8",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "problemMatcher": [
                "$gcc"
            ]
        },
        {
            "label": "Build Release",
            "type": "shell",
            "promptOnClose": true,
            "command": "make -j8",
            "presentation": {
                "reveal": "always",
                "panel": "new"
            },
            "problemMatcher": [
                "$gcc"
            ]
        }`

**Comment by Gamer2020** [comment]
Just want to add that I've been using this in my own repos and it works great.

**Comment by DizzyEggg** [comment]
Agree with Bird there, leaving it as it is for now

**Pull request closed without merging**
